### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by marklar** [diagrams/diagrams-doc#120]
**Section 8.7**
"The Canvas backend..."
should read
"The HTML5 backend..."

**Section 10.1**
V a ~ V2 Double, N a ~ n
Should omit Double

**Comment by byorgey** [comment]
Thanks for the report!

**Comment by marklar** [comment]
Thanks for the wonderful library (and documentation)!

-Mark


2018-03-29 14:08 GMT-07:00 Brent Yorgey <notifications@github.com>:
