### ISSUE TITLE
possible MathJax display issue

### ISSUE THREAD

**Issue by peter-shook** [diagrams/diagrams-doc#122]
When reading the documentation with Chrome, there are backslash open parenthesis and backslash close parenthesis visible, even on the first page of the manual it looks like raw Latex instead of a nice formula.  Could there be a problem with MathJax when creating these pages?

https://archives.haskell.org/projects.haskell.org/diagrams/doc/quickstart.html
**A worked example**
As a way of exhibing a complete example and introducing some additional features of diagrams, consider trying to draw the following picture:
This features a hexagonal arrangement of numbered nodes, with an arrow from node \\(i\\) to node \\(j\\) whenever \\(i < j\\). While we're at it, we might as well make our program generic in the number of nodes, so it generates a whole family of similar diagrams.

https://archives.haskell.org/projects.haskell.org/diagrams/doc/manual.html
Mathematical equations are typeset using MathJax:
\\[\sum_{k=1}^\infty \frac{1}{k^2} = \frac{\pi^2}{6}\]

https://archives.haskell.org/projects.haskell.org/diagrams/doc/vector.html
**Vectors**
Vectors in diagrams are based on the linear package. In two dimensions, you can think of a vector as a pair of coordinates, representing displacements in the \\(x\\) and \\(y\\) directions. Alternatively, you can think of a vector as consisting of a magnitude (length) and a direction (angle).

**Comment by fryguybob** [comment]
Looks like it isn't loading the script.  I get the following in Chrome:

Mixed Content: The page at '
https://archives.haskell.org/projects.haskell.org/diagrams/doc/quickstart.html'
was loaded over HTTPS, but requested an insecure script '
http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'.
This request has been blocked; the content must be served over HTTPS.

**Comment by byorgey** [comment]
Unfortunately this is the old version of the documentation which we no
longer have control over (not even to take it down), and there are still
old links out there.  The up-to-date version of the documentation can be
found at https://diagrams.github.io/ .  MathJax appears to be working just
fine there.

-Brent

**Comment by peter-shook** [comment]
Thanks Brent, I will refer to the newer version instead.
