### ISSUE TITLE
Link goes wrong

### ISSUE THREAD

**Issue by Kaligule** [diagrams/diagrams-doc#82]
In the chapter [Connecting Points](https://github.com/diagrams/diagrams-doc/blob/master/doc/arrow.rst#connecting-points) in the Tutorial for Arrows the word Normalized links to [Diagrams-Prelude-ThreeD](http://projects.haskell.org/diagrams/haddock/Diagrams-Prelude-ThreeD.html#t:Normalized) instead of [Diagrams-Core-Types](http://hackage.haskell.org/package/diagrams-core-1.2.0.5/docs/Diagrams-Core-Types.html#v:Normalized).

**Comment by cchalmers** [comment]
I've changed the links to point to the module things are defined in. Hopefully this will fix all these linking problems once it's rolled out.

**Comment by byorgey** [comment]
@cchalmers what was this comment referring to, when you said "I've changed..."?  What exactly did you change?

**Comment by cchalmers** [comment]
I was referring to #79 but we ended up delaying it. https://github.com/diagrams/diagrams-doc/blob/new-builder/doc/Links.hs

**Comment by cchalmers** [comment]
and https://github.com/diagrams/diagrams-doc/blob/new-builder/doc/pandoc.hs. I used the `Name` to get the module the function was defined in. It's should't be too hard to part to the current version. I'm not sure when the pandoc version will get finished.

**Comment by byorgey** [comment]
Ah, right. Well, I just put a simple workaround in place for now, until we merge that.  Actually, this specific issue also reminds me that `Normalized` is not spelled with a capital N anymore.
